expose:
  type: ClusterIP
  tls:
    enabled: false
  clusterIP:
    name: harbor
    ports:
      httpPort: 80

persistence:
  enabled: true
  resourcePolicy: keep
  persistentVolumeClaim:
    registry:
      size: 10Gi
    jobservice:
      jobLog:
        size: 1Gi
    redis:
      size: 1Gi
    trivy:
      size: 5Gi

database:
  type: external
  external:
    port: "5432"
    username: harbor
    coreDatabase: harbor
    sslmode: disable

redis:
  type: internal

trivy:
  enabled: false

cache:
  enabled: true
  expireHours: 24

logLevel: info
